############# English navigation ##############

# main menu
[[main]]
name = "Tentang"
pageRef = "/about"
weight = 1

[[main]]
name = "Layanan"
pageRef = "/layanan"
weight = 2

[[main]]
weight = 3
name = "Halaman"
hasChildren = true

[[main]]
parent = "Halaman"
name = "Blog"
pageRef = "/blog"

[[main]]
parent = "Halaman"
name = "Promo"
pageRef = "/promo"

# footer menu
[[footer]]
name = "Privacy Policy"
pageRef = "/privacy-policy"
weight = 1
